version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-next
    ports:
      - '3002:3000'
    volumes:
      - .:/app
      - /app/node_modules