name: Build and Deploy to Server

on:
  push:
    branches:
      - main # Adjust the branch as needed

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd technext-landing/
            git pull origin main 
            echo "${{ secrets.SSH_KEY }}" | sudo -S docker-compose down
            echo "${{ secrets.SSH_KEY }}" | sudo -S docker-compose up -d --build

